### ISSUE TITLE
Tests failing on Windows

### ISSUE THREAD

**Issue by SigmaX** [AureumChaos/LEAP#238] opened 2022-12-23 15:59 UTC
While looking into #219 I notice several tests fail on Windows:

![image](https://user-images.githubusercontent.com/313154/209364213-96fab213-6bc3-4599-87e2-a206dc58ee7b.png)

**Comment by SigmaX** [comment] 2023-01-10 15:38
@lukepmccombs

**Comment by lukepmccombs** [comment] 2023-01-10 15:39
I'll pick this up.

**Comment by lukepmccombs** [comment] 2023-01-17 16:17
The first couple errors I have are for the island model scripts. Matplotlib is expecting an integer for `nrows` and doesn't automatically cast `true_rows` from the `viz_plots` function. Easily fixed by a conversion (although it should probably round up).
Relevant tests: test_script_execution on:
island_model.py (viz_plots func)
multitask_island_model.py (viz_plots func)

Looks like several of the issues are caused by the recent changes to gym. `env.reset()` now returns two values, where a lot of the problem code where that is used simply forwards the whole return. Adding `, _` to wherever that is used would fix it.
Relevant tests: test_script_execution on:
neural_network_cartpole.py (executable_rep/problems.py)
pitt_rules_cartpole.py (executable_rep/problems.py)

The last problems I had, and am surprised hadn't come up before, involve distributed. I had two errors when collecting tests and 2 scripts fail because `module 'os' has no attribute 'WNOHANG'`, which is indicative of a Windows incompatibility.
Relevant tests: distributed doctests, test_script_execution on:
simple_async_distributed.py
simple_sync_distributed.py

Session details:
```
platform win32 -- Python 3.10.9, pytest-7.2.1, pluggy-1.0.0
rootdir: C:\Users\luke\LEAP, configfile: pytest.ini
plugins: anyio-3.6.2, c
```

**Comment by lukepmccombs** [comment] 2023-01-25 02:27
Side note as a part of resolving this issue, I have setup github actions on my fork to replace Travis-CI.

The last issue was resolved in develop previously, I have largely fixed the others.

The gym issue is trickier to solve because the convention change hasn't been propagated back to python 3.7 on the version matrix. To support 3.7, we'll have to check versions and swap if need be.

**Comment by markcoletti** [comment] 2023-02-06 19:59
Hopefully will confirm tomorrow that this issue can be closed with the associated merge request resolved.

**Closed** 2023-06-20 15:46 UTC
Labels: bug
