### ISSUE TITLE
cannot visualize live best-of-generation plot for simple example

### ISSUE THREAD

**Issue by dshen109** [AureumChaos/LEAP#121] opened 2021-03-30 18:40 UTC
`simple.py` is missing the `probe` import when `ea_solve` is called with `viz=True`

```
NameError                                 Traceback (most recent call last)
<ipython-input-34-a788e1ed9f16> in <module>
      5 # output captures the sys.stdout
      6 with Capturing() as output:
----> 7     results = ea_solve(
      8         f, bounds=[(-5.12, 5.12) for _ in range(5)], maximize=True,
      9         generations=100, viz=True

~/.virtualenvs/deap/lib/python3.8/site-packages/leap_ec/simple.py in ea_solve(function, bounds, generations, pop_size, mutation_std, maximize, viz, viz_ylim)
     55 
     56     if viz:
---> 57         plot_probe = probe.PopulationPlotProbe(
     58             context, ylim=viz_ylim, ax=plt.gca())
     59         pipeline.append(plot_probe)

NameError: name 'probe' is not defined
```

**Comment by SigmaX** [comment] 2021-03-30 18:49
Hi @dshen109, thanks for reporting!

This is a duplicate of #110 .  It's fixed in the `develop` branch, and will be part of the upcoming v0.6 release.

**Closed by SigmaX** 2021-03-30 18:49 UTC
