### ISSUE TITLE
Live plots don't update

### ISSUE THREAD

**Issue by DBraun** [AureumChaos/LEAP#219] opened 2022-09-09 16:33 UTC
I'm trying `python examples/advanced/island_model.py` but the live plots don't update. They're all white. I'm using Python 3.9.13 Windows, matplotlib 3.5.2, both with PyCharm and in a plain cmd window.

![image](https://user-images.githubusercontent.com/2096055/189397741-c11eae72-80b9-424c-968c-5c78c25d8604.png)

In PyCharm I at least get a first image but it doesn't update.

![image](https://user-images.githubusercontent.com/2096055/189398294-3b9499b0-2354-4329-ab44-279e0420f1df.png)

Same issues with the cgp.py example. I tried various things in `leap_ec/probe.py`'s CartesianPhenotypePlotProbe (confirmed with breakpoints) related to https://stackoverflow.com/questions/35215335/matplotlibs-ion-and-draw-not-working and https://stackoverflow.com/questions/24783530/python-realtime-plotting but couldn't get it working, so I'd appreciate help.

**Comment by SigmaX** [comment] 2022-09-09 16:59
Hmm—I've noticed something similar on macOS that started happening a few months ago.  But this may be different.

We mostly work on Linux, but maybe we can fire up a VM and help debug sometime in the next few weeks.

**Comment by SigmaX** [comment] 2022-12-19 13:25
@DBraun Did you observe this issue with just the island model example(s), or do *all* LEAP examples that have live plots give you the same issue?

**Comment by DBraun** [comment] 2022-12-19 16:31
It's all of the ones with plotting such as examples/simple/*

**Comment by SigmaX** [comment] 2022-12-21 23:18
Okay, putting this one next in my queue.

My first steps will be to
 - set up a Windows VM so I can reproduce locally;
 - then I'll compare to similar observations colleagues have made on macOS,
 - and see if the fix I had fiddled with a few months ago on my local for macOS works, and whether it solves both issues or we have two independent bugs.

**Comment by SigmaX** [comment] 2022-12-23 15:52
Failed to reproduce on Windows 11.  Running in VS Code with Python 3.10 installed from the Windows Store.  I checked both `master` and `develop` branches.

![image](https://user-images.githubusercontent.com/313154/209363100-d0549b6f-a869-4e92-839f-4575e187e169.png)

I do see a few of the tests fail on Windows

**Comment by DBraun** [comment] 2022-12-24 16:16
I had 3.9 from python.org on Windows 11. I’ll see if I can retest and then test 3.10 sometime.

**Comment by SigmaX** [comment] 2023-01-10 15:31
Closing this for the time being since we've been unable to reproduce it—happy to revisit it if and when we get more info!

**Closed by SigmaX** 2023-01-10 15:31 UTC
Labels: bug
